spring:
  datasource:
    tomcat:
      remove-abandoned-timeout: 60
      remove-abandoned: true
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://patition-db.ckuzxdryb7hz.ap-northeast-2.rds.amazonaws.com:3307/testdb?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: gist2021
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
  profiles:
    include:
      - aws
      - credentials
#spring.datasource.url=jdbc:mysql://database-2.ckr9u04uxydd.us-east-2.rds.amazonaws.com:3307/test-db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul

