spring:
  profiles:
    active: local
server.servlet.session.cookie:
  http-only: true
  path: /
  secure: true
  sameSite: None
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: dev
    import: ./privates/application-dev-db.yml, ./privates/application-dev-mail.yml
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
request:
  origins: https://localhost:3000, https://dev.gist-petition.com