spring:
  profiles:
    active: local

server.servlet.session.cookie:
  http-only: true
  path: /
  secure: true

---

spring:
  config:
    activate:
      on-profile: local
    import: datasoruce/application-docker-mysql.yml
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: test
    import: datasoruce/application-docker-mysql.yml
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---

spring:
  config:
    activate:
      on-profile: dev
    import: datasoruce/application-docker-mysql.yml, ./privates/application-dev-mail.yml
swagger:
  host: dev-api.gist-petition.com
  protocol: https

request:
  origins: https://localhost:3000, https://localhost:3001, https://dev.gist-petition.com, https://dev-staff.gist-petition.com

---

spring:
  config:
    activate:
      on-profile: prod
    import: ./privates/application-prod-db.yml, ./privates/application-prod-mail.yml
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true

  server.servlet.session.cookie:
    sameSite: Lax

swagger:
  host: api.gist-petition.com
  protocol: https

request:
  origins: https://www.gist-petition.com, https://staff.gist-petition.com